/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/laptop.glb
Author: Rasmus (https://sketchfab.com/Rasmus82)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-7fbe17a5a5dd41538c81c4ad8a5083cf
Title: Laptop
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export default function Laptop({ pos, rot, ...props }) {
  const { nodes, materials } = useGLTF("./models/laptop.glb");
  const laptopScreen = useTexture("./images/p1.jpg");

  return (
    <group
      {...props}
      dispose={null}
      scale={1}
      position={pos ? pos : [0, 0, 0]}
      rotation={rot ? rot : [0, 0, 0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Buttons}>
          {/* <meshBasicMaterial color="gray" /> */}
        </mesh>
        <mesh geometry={nodes.Object_3.geometry} material={materials.screen}>
          <meshStandardMaterial
            // map={laptopScreen}
            color={"black"}
            roughness={1}
            metalness={1}
          />
        </mesh>
        <mesh
          rotation={[Math.PI / 2, 0, -0.41]}
          position={[2.2, 0, 1.2]}
          scale={0.23}
        >
          <boxGeometry args={[0.01, 11, 16]} />
          <meshStandardMaterial
            map={laptopScreen}
            roughness={1}
            metalness={1}
          />
        </mesh>

        {/* 9:16 aspect ratio screen  */}
        {/* <mesh
          rotation={[Math.PI / 2, 0, -0.41]}
          position={[2.3, 0, 1.4]}
          scale={0.23}
        >
          <boxGeometry args={[0.01, 9, 16]} />
          <meshStandardMaterial
            map={laptopScreen}
            roughness={1}
            metalness={1}
          />
        </mesh> */}

        {/* <mesh
          rotation={[Math.PI / 2, 0, -0.41]}
          position={[1.8, 0, 0.25]}
          scale={0.23}
        >
          <boxGeometry args={[0.01, 2, 16]} />
          <meshStandardMaterial color="gray">
            <RenderTexture attach="map">
              <PerspectiveCamera makeDefault position={[0, 0, 5]} />
              <Text fontSize={0.5} color="orange">
                Marco Fijan
              </Text>
            </RenderTexture>
          </meshStandardMaterial>
        </mesh> */}
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          // material={materials.Metal}
        >
          <meshStandardMaterial
            color="black
          "
            roughness={0.3}
            metalness={1}
          />
        </mesh>
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Keyboard}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Keyboard}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Keyboard}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          // material={materials.LabTop_Base}
        >
          <meshStandardMaterial color="#9c9c9c" roughness={0.5} metalness={1} />
        </mesh>
        <mesh
          geometry={nodes.Object_10.geometry}

          // material={materials.LabTop_Base}
        >
          <meshStandardMaterial color="#9c9c9c" roughness={0.5} metalness={1} />
        </mesh>
        <mesh
          geometry={nodes.Object_11.geometry}
          // material={materials.Mouse_PAD}
        >
          <meshBasicMaterial color="#585858" />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("./models/laptop.glb");
