/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/laptopv2.glb
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useTexture, useScroll } from '@react-three/drei'


export default function Laptop(props) {
  const { nodes, materials } = useGLTF('./models/laptopv2.glb')
  const [laptopScreenPath, setLaptopScreenPath] = useState("./images/p1.jpg");
  const rotation = {open: {rot: [Math.PI / 2, 0, 0], pos: [0, 0.04, -0.12]}, close: {rot: [Math.PI / 0.94, 0, 0], pos: [0, 0.01, -0.08]} }
  const [isOpen, setOpen] = useState(true)
  const laptopScreenTexture = useTexture(laptopScreenPath);
  
  return (
    <group {...props} dispose={null} scale={10}>
      <group scale={[0.19, 0.15, 0.12]}>
        <mesh geometry={nodes.Cover_Plane.geometry} material={materials['Cover Silver']} />
        <mesh geometry={nodes.Cover_Plane_1.geometry}  ><meshStandardMaterial
            color='#585858'
            roughness={1}
            metalness={1}
          /></mesh>
      </group>
      <mesh geometry={nodes.Rubber_Strip.geometry} material={nodes.Rubber_Strip.material} scale={[0.16, 0, 0]} />
      <mesh geometry={nodes.Keyboard.geometry} position={[0, 0.01, -0.03]} rotation={[0.03, 0, 0]} scale={0.0055} >
        <meshStandardMaterial
            color='#585858'
            roughness={1}
            metalness={1}
          />
      </mesh>
      <group position={rotation.open.pos} rotation={rotation.open.rot} scale={[0.18, 0.21, 0.11]}>
        <mesh geometry={nodes.Display_Plane.geometry} material={materials['Cover Silver']} />
        <mesh geometry={nodes.Display_Plane_1.geometry} >
          <meshStandardMaterial
            map={laptopScreenTexture}
            roughness={1}
            metalness={1}
          /></mesh>
      </group>
    </group>
  )
}

useGLTF.preload('./models/laptopv2.glb')
